server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  # datasource:
  #   url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  #   username: root
  #   password: root

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: group-id-linknamu
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0 # 오류시 재시도 횟수

logging:
  level:
    '[com.example.kakao]': INFO
    '[org.hibernate.type]': TRACE
