apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka-port
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          resources:
            requests:
              memory: 500Mi
          ports:
            - containerPort: 9092
              name: kafka-port
          env:
            - name: KAFKA_ADVERTIESD_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_CREATE_TOPICS
              value: |
                notion:1:1
                google_docs:1:1
                kakao:1:1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi